apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zk-slack.fullname" . }}
  labels:
    {{- include "zk-slack.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zk-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zk-auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zk-slack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.dockerBase }}/{{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: pl-db-secrets
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /opt/zk-auth-pixie-configmap.yaml
            name: zk-auth-pixie-configmap
            subPath: zk-auth-pixie-configmap.yaml
          - mountPath: /opt/zk-auth-configmap.yaml
            name: zk-auth-configmap
            subPath: zk-auth-configmap.yaml
          env:
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: zk-cluster-configurations-secret
                  key: openAI_key
            - name: PINECONE_ENV
              valueFrom:
                secretKeyRef:
                  name: zk-cluster-configurations-secret
                  key: pinecone_env
            - name: PINECONE_KEY
              valueFrom:
                secretKeyRef:
                  name: zk-cluster-configurations-secret
                  key: pinecone_key
            - name: PINECONE_INDEX
              valueFrom:
                secretKeyRef:
                  name: zk-cluster-configurations-secret
                  key: pinecone_index
      volumes:
      - configMap:
          name: zk-auth-pixie-configmap
        name: zk-auth-pixie-configmap
      - configMap:
          name: zk-auth-configmap
        name: zk-auth-configmap
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
