apiVersion: v1
data:
  zk-auth-pixie-configmap.yaml: |+
    url:
      protocol: https
      base: {{ .Values.pixie.base }}.{{ .Values.global.zkcloud.host }}
      kratos: kratos
      work: work
      port: 443
      def_state: 1ae81750d4d34bb9b96a9fc0a6b4eff9
    timeouts:
      operation: 3
      login: 3
    kratos:
      create: /admin/identities
      recovery_link: /admin/recovery/link
      delete_link: /admin/identities
    work:
      login: /oauth/hydra/oauth2/auth?client_id=auth-code-client&redirect_uri=https%3A%2F%2Fwork.$PX_DOMAIN%2Fauth%2Fcallback&response_type=token&scope=vizier&state=$STATE&prompt=login
kind: ConfigMap
metadata:
  name: zk-auth-pixie-configmap
