apiVersion: v1
kind: Secret
metadata:
  name: zk-cluster-configurations-secret
type: Opaque
data:
  openAI_key: {{ .Values.zkGpt.openAI_key }}
  pinecone_key: {{ .Values.zkGpt.pinecone_key }}
  pinecone_env: {{ .Values.zkGpt.pinecone_env }}
  pinecone_index: {{ .Values.zkGpt.pinecone_index }}
  clientId: {{ .Values.slack.clientId }}
  clientSecret: {{ .Values.slack.clientSecret }}
  redirectUri: {{ .Values.slack.redirectUri }}
  signingSecret: {{ .Values.slack.signingSecret }}
  scopes: {{ .Values.slack.scopes }}
