apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-slack-configmap

data: 
  zk-auth-configmap.yaml: |-
    server:
      port: 3000
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        password: "{{ .Values.postgres.password }}"
        #    url: jdbc:postgresql://postgres.plc.svc.cluster.local:5432/pl
        url: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/pl"
        username: "{{ .Values.postgres.user }}"
      jpa:
        hibernate:
          ddl-auto: update
      entity-scan:
        base-package: com.zerok.slackintegration.entities

    logging.level:
      com.slack.api: DEBUG

    slack:
      scopes: "{{ .Values.slack.scopes }}"
      clientId: "{{ .Values.slack.clientId }}"    #"2752528759122.5974500920640"
      clientSecret: "{{ .Values.slack.clientSecret }}" #"5a73604214192016035cf5871e1932a9"
      redirectUri: "{{ .Values.slack.redirectUri }}"
      signingSecret: "{{ .Values.slack.signingSecret }}" #"09b15216bb3371d41f72b4d4415b132f"
      appId: "{{ .Values.slack.appId }}"  #"A05UNEQT2JU"

    zeroKDashboard:
      host: {{ .Values.zeroKDashboard.host }}