apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-auth-configmap

data: 
  zk-auth-configmap.yaml: |-


    database:
      host: localhost
      port: 5432

    server:
      host: localhost
      port: 80

    logs:
      color: true
      level: DEBUG

    auth:
      expiry: 1800
      adminEmail: master+ORG_NAME@zerok.ai

    http:
      debug: true

    pixie:
      local: false
      config: /opt/zk-auth-pixie-configmap.yaml

    router:
      zkApiServer: "{{ .Values.router.zkApiServer }}"
      zkDashboard: "{{ .Values.router.zkDashboardUrl }}.{{ .Values.global.zkcloud.host }}"
      zkWSP: "{{ .Values.router.zkWSP }}"
      zkWSPRouter:
        zkAxon:
          identifier: /axon
          endpoint: "{{ .Values.router.zkWSPRouter.zkAxon.endpoint }}"
        zkGPT:
          identifier: /gpt
          endpoint: "{{ .Values.router.zkWSPRouter.zkGPT.endpoint }}"

    redis:
      host: "{{ .Values.redis.host }}"
      port: {{ .Values.redis.port }}
      readTimeout: 20

    suprsend:
      workspaceKey: "{{ .Values.suprsend.workspaceKey }}"
      workspaceSecret: "{{ .Values.suprsend.workspaceSecret }}"

    postgres:
      host: "{{ .Values.postgres.host }}"
      port: {{ .Values.postgres.port }}
      user: "{{ .Values.postgres.user }}"
      password: "{{ .Values.postgres.password }}"
      dbname: "{{ .Values.postgres.database }}"
