apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-slack-configmap

data: 
  zk-auth-configmap.yaml: |-
    server:
      port: 3000
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        password: "{{ .Values.postgres.password }}"
        #    url: jdbc:postgresql://postgres.plc.svc.cluster.local:5432/pl
        url: jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/pl
        username: "{{ .Values.postgres.user }}"
      jpa:
        hibernate:
          ddl-auto: update
      entity-scan:
        base-package: com.zerok.slackintegration.entities

    logging.level:
      com.slack.api: DEBUG

    slack:
      scopes:
        {{- range .Values.organizations }}
        - {{ . }}
        {{- end }}
      clientId: "{{ .Values.slack.clientId }}"
      clientSecret: "{{ .Values.slack.clientSecret }}"
      redirectUri: "{{ .Values.slack.redirectUri }}"
      signingSecret: "{{ .Values.slack.signingSecret }}"
      appId: "{{ .Values.slack.appId }}"

    zeroKDashboard:
      host: {{ .Values.zeroKDashboard.host }}