apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-slack-configmap

data: 
  zk-slack-configmap.yaml: |-
    server:
      port: 3000
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: {{ .Values.postgres.url }}
        password: {{ .Values.postgres.password }}
        #    url: jdbc:postgresql://postgres.plc.svc.cluster.local:5432/pl
        username: {{ .Values.postgres.user }}
      jpa:
        database: postgresql
        show-sql: true
        generate-ddl: true
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      entity-scan:
        base-package: com.zerok.slackintegration.entities

    logging.level:
      com.slack.api: DEBUG

    slack:
      scopes:
        {{- range .Values.organizations }}
        - {{ . }}
        {{- end }}
      clientId: "{{ .Values.slack.clientId }}"
      clientSecret: "{{ .Values.slack.clientSecret }}"
      redirectUri: "{{ .Values.slack.redirectUri }}"
      signingSecret: "{{ .Values.slack.signingSecret }}"
      appId: "{{ .Values.slack.appId }}"

    zeroKDashboard:
      host: {{ .Values.zeroKDashboard.host }}