# Purpose: This action is triggered through a git push and does all it takes to  deploy the app
# on a cluster
name: dev-build-push-deploy
on:
  push:
    tags: #dev/<CLUSTER>/<DOCKER-TAG-OR-VERSION>
      - 'dev/**'

  #  # Uncomment the following code for testing
#  workflow_dispatch:
#    inputs:
#      DOCKER_TAG:
#        description: 'Docker Image Tag'
#        required: true
#        default: '0.0.9-helmtest'
#      GKE_CLUSTER:
#        description: 'Cluster Name'
#        required: true
#        default: 'devclient03'
env:
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
  APP_NAME: ${{ vars.APP_NAME }}
  NAMESPACE: ${{ vars.NAMESPACE }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}

jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-dev-init.yml@main
    with:
      GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}

  build-push:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-build-push.yml@main
    with:
      VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.CLUSTERNAME }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      MAKE_TARGET: 'ci-cd-build'
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_DEV }}
    needs: init

  deploy:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-deploy.yml@main
    with:
      CLUSTERNAME: ${{ needs.init.outputs.CLUSTERNAME }}
      VERSION: ${{ needs.init.outputs.VERSION }}
      MIGRATION_VERSION: ${{ needs.init.outputs.VERSION }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
    secrets:
      HELM_SECRETS_ARGS: ${{ format('--set=slack.clientId={0} --set=slack.clientSecret={1} --set=slack.signingSecret={2} --set=slack.appId={3}', secrets.SLACK_CLIENT_ID, secrets.SLACK_CLIENT_SECRET, secrets.SLACK_SIGNING_SECRET, secrets.SLACK_APP_ID) }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_DEV }}
    needs: [init,build-push]
