# Purpose: This action is triggered manually and is meant for the case where
# the build happens through this action and the deployment is done through CLI
name: dev-build-push
on:
  workflow_dispatch:
    inputs:
      DOCKER_TAG:
        description: 'Docker Image Tag'
        required: true
        default: '0.0.9-helmtest'
      GKE_CLUSTER:
        description: 'Cluster Name'
        required: true
        default: 'devclient03'

jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-dev-init.yml@main
    with:
      GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}

  build-push:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-build-push.yml@main
    with:
      VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.CLUSTERNAME }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      MAKE_TARGET: 'ci-cd-build'
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_DEV }}
    needs: init